server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.229.1:8848 #nacos address
    gateway:
      routes:
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: article-service
          uri: lb://ArticleService
          predicates:
            - Path=/article/**
        - id: comment-service
          uri: lb://CommentService
          predicates:
            - Path=/comment/**
        - id: comment-websocket-route
          uri: lb://CommentService
          predicates:
            - Path=/ws-comment-service/**
#            - Method=WEBSOCKET # 添加WebSocket谓词
          filters:
            - RewritePath=/ws-comment-service/(?<segment>.*), /websocket/$\{segment} # 重写路径，如果WebSocket路径需要调整
      globalcors: #Global cross-domain processing
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]': # ??????????
            allowedOrigins: "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*" # ???????
            allowCredentials: false # ????cookie
            maxAge: 36000 # ??????????????
token:
  jwt:
    signing-key: mySecretkey
    expire: 36000000



